### ISSUE TITLE
Rename Devices

### ISSUE THREAD

**Issue by equiman** [Fukkei/zmk-split-battery#3]
Is there a way to rename the devices?

![image](https://user-images.githubusercontent.com/933393/215685968-8da10c27-b36c-486b-8cdd-76b2152f747d.png)

Instead of central and peripheral to something like left, and right?

I've searched on the code but I did not find something related to... or do those names come directly from the ZMK firmware?

**Comment by Fukkei** [comment]
Yes, the names are pulled from GattCharacteristic::UserDescription in BatteryMonitor.cs. They are set by ZMK, look here:
https://github.com/zmkfirmware/zmk/pull/1243/files#diff-b8b12f3bd378d52934c2db45e02bda186fc70a556ec4c715357a3ef630a29f3eR47

**Comment by equiman** [comment]
Perfect, thanks. I'll try to change it from that.

**Comment by equiman** [comment]
It works! Thanks

![image](https://user-images.githubusercontent.com/933393/215966923-60686fb6-6020-44d5-a3cf-ef5e4c1131d0.png)
